const english = {
  goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening', welcomeBack: 'Welcome back',
  dayStreak: 'day streak', thisWeek: 'This week', todaysWorkout: "Today's workout", seeAll: 'See all', workoutComplete: 'Workout complete',
  todaysSession: "Today's session", exercises: 'exercises', completedMessage: 'Nice work today. Your streak is locked in — rest well and come back stronger.', viewWorkout: 'View workout', loading: 'Loading...',
  yourWorkout: 'Your workout', startWorkout: 'Start workout', restDay: 'Rest day', recoveryMessage: 'Recovery is part of the plan. Your next workout is on',
  nutritionMeals: 'Nutrition & Meals', details: 'Details', calories: 'Calories', protein: 'Protein', carbs: 'Carbs', fats: 'Fats', mealPlan: 'Your meal plan', todaysMeals: "Tap to view today's meals",
  community: 'Community', noPosts: 'No posts yet — be the first!', trainers: 'Trainers', challenges: 'Challenges', noChallenges: 'No challenges yet', posts: 'posts', view: 'View',
  all: 'All', general: 'General', progress: 'Progress', questions: 'Questions', share: 'Share', save: 'Save', report: 'Report', cancel: 'Cancel', postOptions: 'Post options', comingSoon: 'Coming soon', savePostsMessage: 'Saving posts will be available in a future update.', reported: 'Reported', reportThanks: "Thanks — we'll review this post.", error: 'Error', couldNotLoadPosts: 'Could not load posts',
  workouts: 'Workouts', myPlan: 'My Plan', forYou: 'For You', home: 'Home', gym: 'Gym', fasting: 'Fasting', library: 'Library', todaysPick: "Today's pick", craftedForYou: 'Crafted for you', loadingPlan: 'Loading plan...', completed: 'Completed', missed: 'Missed', today: 'Today',
  homeWorkouts: 'Home workouts', noGym: 'No gym needed', gymWorkouts: 'Gym workouts', fullEquipment: 'Full equipment', fastingWorkouts: 'Fasting workouts', lowIntensity: 'Low intensity, high benefit', exerciseLibrary: 'Exercise Library', discoverExercises: 'Discover New Exercises', browseExercises: 'Browse all exercises', soon: 'soon',
  monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday', friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday',
  mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun', push: 'Push Day', pull: 'Pull Day', legs: 'Leg Day', upper: 'Upper Body', lower: 'Lower Body', fullBody: 'Full Body',
  upperBody: 'Upper Body', lowerBody: 'Lower Body', core: 'Core', biceps: 'Biceps', triceps: 'Triceps', cardio: 'Cardio', intenseCardio: 'Intense Cardio', chest: 'Chest', backMuscle: 'Back', shoulders: 'Shoulders', legsCategory: 'Legs', lightFullBody: 'Light Full Body', coreBalance: 'Core and Balance', lowIntensityCardio: 'Low Intensity Cardio',
  nextLevel: 'Your next level\nStarts here.', allInOne: 'Your workouts, meals, progress and our fitness community all in one place.', getStarted: 'Get started', alreadyAccount: 'I already have an account', loginTitle: 'Welcome back', loginSubtitle: 'Log in to continue your journey', emailUsername: 'Email or username', password: 'Password', login: 'Log in', loggingIn: 'Logging in...', noAccount: "Don't have an account?", signUp: 'Sign up', fillFields: 'Please fill in all fields', almostThere: 'Almost there.', createAccountSubtitle: 'Create your account to save your plan and get started.', fullName: 'Full name', username: 'Username', emailAddress: 'Email address', passwordMustHave: 'Password must have:', atLeastEight: '• At least 8 characters', oneNumber: '• At least one number', oneCapital: '• At least one capital letter', referralOptional: 'Referral code (optional)', createAccount: 'Create account', creatingAccount: 'Creating account...', haveAccount: 'Already have an account?',
  getToKnowYou: "Let's get to know you.", onboardingIntro: 'A few quick questions so we can build a plan that actually works for you.', letsGo: "Let's go", continue: 'Continue', back: 'Back', fitnessLevelQuestion: 'What is your fitness level?', fitnessLevelSub: 'Be honest — this helps us get your plan right.', beginner: 'Beginner', beginnerSub: 'Just starting out · 0–6 months training', intermediate: 'Intermediate', intermediateSub: '6 months to 2 years training', advanced: 'Advanced', advancedSub: '2+ years of training', goalQuestion: 'What is your main goal?', goalSub: "We'll build your plan around this.", loseWeight: 'Lose weight', loseWeightSub: 'Burn fat and get leaner', buildMuscle: 'Build muscle', buildMuscleSub: 'Get stronger and bigger', stayActive: 'Stay active', stayActiveSub: 'Keep moving and feel good', improveFitness: 'Improve fitness', improveFitnessSub: 'Build endurance and stamina',
  daysQuestion: 'How many days a week can you work out?', daysSub: 'Be realistic — consistency beats intensity.', twoDays: '2 days', threeDays: '3 days', fourDays: '4 days', fiveDays: '5+ days', lightSchedule: 'Light schedule', goodBalance: 'Good balance', seriousCommitment: 'Serious commitment', fullDedication: 'Full dedication', whichDays: 'Which days?', selectDays: 'Select exactly', selected: 'selected', durationQuestion: 'How long can you work out?', durationSub: "We'll fit your plan around your schedule.", minutes30: '30 minutes', minutes45: '45 minutes', minutes60: '60+ minutes', minutes80: '1 hour 20 minutes', quickSession: 'Quick session', popularChoice: 'Most popular choice', solidSession: 'Solid session', equipmentQuestion: 'What equipment do you have?', equipmentSub: "We'll build your plan around what you have access to.", fullGym: 'Full gym access', fullGymSub: 'All equipment available', dumbbellsHome: 'Dumbbells at home', dumbbellsHomeSub: 'Home setup with weights', noEquipment: 'No equipment', noEquipmentSub: 'Bodyweight only', gymHome: 'Both gym and home', gymHomeSub: 'I switch between both', foodQuestion: 'What are your food choices?', foodSub: 'Select all that apply to you.', meatEater: 'Meat eater', meatSub: 'I eat meat regularly', vegetarian: 'Vegetarian', vegetarianSub: "I don't eat meat", regularFasting: 'I fast regularly', fastingSub: 'Weekly or seasonal fasting', ethiopianDiet: 'Ethiopian diet', ethiopianDietSub: 'Injera, shiro, tibs and more',
  personalQuestion: 'Tell us about yourself.', personalSub: 'This helps us personalise your plan accurately.', analysing: 'Analysing your profile...', analysingSub: 'Calculating your ideal weight based on your height, age and goal', gender: 'Gender', male: 'Male', female: 'Female', age: 'Age', heightCm: 'Height (cm)', currentWeight: 'Current weight (kg)', calculateIdeal: 'Calculate my ideal weight', idealWeight: 'Your ideal weight', idealExplanation: 'Based on your height, age and goal this is a healthy and achievable target weight for you.', accept: 'Accept', setOwnGoal: 'Set my own goal', goalWeightSet: 'Goal weight set to', goalWeight: 'My goal weight (kg)', confirmGoal: 'Confirm goal', locationQuestion: 'Where are you based?', locationSub: 'Helps us connect you with your local community.', unitedKingdom: 'United Kingdom', unitedKingdomSub: 'England, Scotland, Wales, N. Ireland', unitedStates: 'United States', unitedStatesSub: 'All US states', europe: 'Europe', europeSub: 'Sweden, Germany, Norway and more', canada: 'Canada', canadaSub: 'All Canadian provinces', ethiopia: 'Ethiopia', ethiopiaSub: 'Based in Ethiopia', somewhereElse: 'Somewhere else', otherCountry: 'Other country', injuryQuestion: 'Any injuries or limitations?', injurySub: "We'll make sure your plan works around them. Skip if none.", backPain: 'Back pain', backPainSub: 'Lower or upper back issues', kneeProblems: 'Knee problems', kneeSub: 'Pain or previous injury', shoulderIssues: 'Shoulder issues', shoulderSub: 'Rotator cuff or joint pain', wristPain: 'Wrist pain', wristSub: 'Wrist or forearm discomfort', anklePain: 'Ankle pain', ankleSub: 'Ankle or foot issues', noInjuries: 'No injuries', noInjuriesSub: "I'm good to go", other: 'Other', otherInjurySub: 'Tap to describe your limitation', describeInjury: 'Describe your injury or limitation...', finish: 'Finish', planReady: 'Your plan is ready.', planReadySub: "Welcome to Fitopia. Everything has been personalised for you. Let's get to work.", customPlan: 'Custom plan', aiCoach: 'AI Coach', seePlan: 'See my plan',
};

const amharic = {
  goodMorning: 'እንደምን አደሩ', goodAfternoon: 'እንደምን ዋሉ', goodEvening: 'እንደምን አመሹ', welcomeBack: 'እንኳን ደህና መጡ',
  dayStreak: 'ቀን ተከታታይ', thisWeek: 'በዚህ ሳምንት', todaysWorkout: 'የዛሬ ልምምድ', seeAll: 'ሁሉንም ይመልከቱ', workoutComplete: 'ልምምዱ ተጠናቋል',
  todaysSession: 'የዛሬ ስልጠና', exercises: 'ልምምዶች', completedMessage: 'ዛሬ ጥሩ ስራ ሰርተዋል። ተከታታይነትዎ ተጠብቋል፤ በደንብ ያርፉ እና በብርታት ይመለሱ።', viewWorkout: 'ልምምዱን ይመልከቱ', loading: 'በመጫን ላይ...',
  yourWorkout: 'የእርስዎ ልምምድ', startWorkout: 'ልምምድ ይጀምሩ', restDay: 'የእረፍት ቀን', recoveryMessage: 'ማገገም የእቅዱ አካል ነው። ቀጣዩ ልምምድዎ',
  nutritionMeals: 'ምግብ እና ምግቦች', details: 'ዝርዝሮች', calories: 'ካሎሪ', protein: 'ፕሮቲን', carbs: 'ካርቦሃይድሬት', fats: 'ቅባቶች', mealPlan: 'የምግብ እቅድዎ', todaysMeals: 'የዛሬ ምግቦችን ለማየት ይንኩ',
  community: 'ማህበረሰብ', noPosts: 'እስካሁን ፖስቶች የሉም — የመጀመሪያው ይሁኑ!', trainers: 'አሰልጣኞች', challenges: 'ፈተናዎች', noChallenges: 'እስካሁን ፈተናዎች የሉም', posts: 'ፖስቶች', view: 'ይመልከቱ',
  all: 'ሁሉም', general: 'አጠቃላይ', progress: 'እድገት', questions: 'ጥያቄዎች', share: 'አጋራ', save: 'አስቀምጥ', report: 'ሪፖርት አድርግ', cancel: 'ሰርዝ', postOptions: 'የፖስት አማራጮች', comingSoon: 'በቅርብ ጊዜ', savePostsMessage: 'ፖስቶችን ማስቀመጥ በወደፊት ዝማኔ ይገኛል።', reported: 'ሪፖርት ተደርጓል', reportThanks: 'እናመሰግናለን — ይህን ፖስት እንገመግማለን።', error: 'ስህተት', couldNotLoadPosts: 'ፖስቶችን መጫን አልተቻለም',
  workouts: 'ልምምዶች', myPlan: 'የእኔ እቅድ', forYou: 'ለእርስዎ', home: 'ቤት', gym: 'ጂም', fasting: 'ጾም', library: 'ቤተ መጻሕፍት', todaysPick: 'የዛሬ ምርጫ', craftedForYou: 'ለእርስዎ የተዘጋጀ', loadingPlan: 'እቅድ በመጫን ላይ...', completed: 'ተጠናቋል', missed: 'አምልጧል', today: 'ዛሬ',
  homeWorkouts: 'የቤት ልምምዶች', noGym: 'ጂም አያስፈልግም', gymWorkouts: 'የጂም ልምምዶች', fullEquipment: 'ሙሉ መሳሪያዎች', fastingWorkouts: 'የጾም ልምምዶች', lowIntensity: 'ዝቅተኛ ጥንካሬ፣ ከፍተኛ ጥቅም', exerciseLibrary: 'የልምምድ ቤተ መጻሕፍት', discoverExercises: 'አዳዲስ ልምምዶችን ያግኙ', browseExercises: 'ሁሉንም ልምምዶች ይመልከቱ', soon: 'በቅርብ ጊዜ',
  monday: 'ሰኞ', tuesday: 'ማክሰኞ', wednesday: 'ረቡዕ', thursday: 'ሐሙስ', friday: 'ዓርብ', saturday: 'ቅዳሜ', sunday: 'እሁድ',
  mon: 'ሰኞ', tue: 'ማክ', wed: 'ረቡ', thu: 'ሐሙ', fri: 'ዓር', sat: 'ቅዳ', sun: 'እሁ', push: 'የግፊት ቀን', pull: 'የመሳብ ቀን', legs: 'የእግር ቀን', upper: 'የላይኛው አካል', lower: 'የታችኛው አካል', fullBody: 'ሙሉ አካል',
  upperBody: 'የላይኛው አካል', lowerBody: 'የታችኛው አካል', core: 'የሰውነት መሀል', biceps: 'ባይሴፕስ', triceps: 'ትራይሴፕስ', cardio: 'ካርዲዮ', intenseCardio: 'ከፍተኛ ካርዲዮ', chest: 'ደረት', backMuscle: 'ጀርባ', shoulders: 'ትከሻዎች', legsCategory: 'እግሮች', lightFullBody: 'ቀላል ሙሉ አካል', coreBalance: 'መሀል እና ሚዛን', lowIntensityCardio: 'ዝቅተኛ ካርዲዮ',
  nextLevel: 'ወደ ቀጣዩ ደረጃዎ\nእዚህ ይጀምራል።', allInOne: 'የእርስዎ ልምምዶች፣ ምግቦች፣ እድገት እና የጤና ማህበረሰባችን ሁሉም በአንድ ቦታ።', getStarted: 'ይጀምሩ', alreadyAccount: 'መለያ አለኝ', loginTitle: 'እንኳን ደህና መጡ', loginSubtitle: 'ጉዞዎን ለመቀጠል ይግቡ', emailUsername: 'ኢሜይል ወይም የተጠቃሚ ስም', password: 'የይለፍ ቃል', login: 'ይግቡ', loggingIn: 'በመግባት ላይ...', noAccount: 'መለያ የለዎትም?', signUp: 'ይመዝገቡ', fillFields: 'እባክዎ ሁሉንም መስኮች ይሙሉ', almostThere: 'ሊጠናቀቅ ነው።', createAccountSubtitle: 'እቅድዎን ለማስቀመጥ እና ለመጀመር መለያዎን ይፍጠሩ።', fullName: 'ሙሉ ስም', username: 'የተጠቃሚ ስም', emailAddress: 'የኢሜይል አድራሻ', passwordMustHave: 'የይለፍ ቃል ሊኖረው የሚገባ:', atLeastEight: '• ቢያንስ 8 ቁምፊዎች', oneNumber: '• ቢያንስ አንድ ቁጥር', oneCapital: '• ቢያንስ አንድ ካፒታል ፊደል', referralOptional: 'የግብዣ ኮድ (አማራጭ)', createAccount: 'መለያ ይፍጠሩ', creatingAccount: 'መለያ በመፍጠር ላይ...', haveAccount: 'መለያ አለዎት?',
  getToKnowYou: 'ስለ እርስዎ እንወቅ።', onboardingIntro: 'ለእርስዎ በትክክል የሚሰራ እቅድ እንድንሰራ ጥቂት ፈጣን ጥያቄዎች።', letsGo: 'እንጀምር', continue: 'ይቀጥሉ', back: 'ተመለስ', fitnessLevelQuestion: 'የእርስዎ የአካል ብቃት ደረጃ ምንድን ነው?', fitnessLevelSub: 'እውነተኛ ይሁኑ — ይህ እቅድዎን በትክክል እንድናዘጋጅ ይረዳናል።', beginner: 'ጀማሪ', beginnerSub: 'አሁን የጀመሩ · 0–6 ወር ልምምድ', intermediate: 'መካከለኛ', intermediateSub: 'ከ6 ወር እስከ 2 ዓመት ልምምድ', advanced: 'የላቀ', advancedSub: '2+ ዓመት ልምምድ', goalQuestion: 'ዋና ግብዎ ምንድን ነው?', goalSub: 'እቅድዎን በዚህ ዙሪያ እንገነባለን።', loseWeight: 'ክብደት ይቀንሱ', loseWeightSub: 'ስብ ያቃጥሉ እና ቀጭን ይሁኑ', buildMuscle: 'ጡንቻ ይገንቡ', buildMuscleSub: 'ጠንካራ እና ትልቅ ይሁኑ', stayActive: 'ንቁ ይሁኑ', stayActiveSub: 'እንቅስቃሴዎን ይቀጥሉ እና ጥሩ ይሰማዎት', improveFitness: 'ብቃት ያሻሽሉ', improveFitnessSub: 'ጽናት እና ብርታት ይገንቡ',
  daysQuestion: 'በሳምንት ስንት ቀን ልምምድ ማድረግ ይችላሉ?', daysSub: 'እውነተኛ ይሁኑ — ቀጣይነት ከጥንካሬ ይበልጣል።', twoDays: '2 ቀን', threeDays: '3 ቀን', fourDays: '4 ቀን', fiveDays: '5+ ቀን', lightSchedule: 'ቀላል መርሃ ግብር', goodBalance: 'ጥሩ ሚዛን', seriousCommitment: 'ከፍተኛ ቁርጠኝነት', fullDedication: 'ሙሉ ቁርጠኝነት', whichDays: 'የትኞቹ ቀናት?', selectDays: 'በትክክል ይምረጡ', selected: 'ተመርጠዋል', durationQuestion: 'ምን ያህል ጊዜ ልምምድ ማድረግ ይችላሉ?', durationSub: 'እቅድዎን ከመርሃ ግብርዎ ጋር እናስማማዋለን።', minutes30: '30 ደቂቃ', minutes45: '45 ደቂቃ', minutes60: '60+ ደቂቃ', minutes80: '1 ሰዓት 20 ደቂቃ', quickSession: 'ፈጣን ስልጠና', popularChoice: 'በብዛት የሚመረጥ', solidSession: 'ጥሩ ስልጠና', equipmentQuestion: 'ምን መሳሪያዎች አሉዎት?', equipmentSub: 'እቅድዎን በሚደርሱበት መሳሪያ መሰረት እንሰራለን።', fullGym: 'ሙሉ የጂም መዳረሻ', fullGymSub: 'ሁሉም መሳሪያዎች ይገኛሉ', dumbbellsHome: 'በቤት ዱምቤል', dumbbellsHomeSub: 'በክብደት መሳሪያ የተዘጋጀ ቤት', noEquipment: 'መሳሪያ የለም', noEquipmentSub: 'የሰውነት ክብደት ብቻ', gymHome: 'ጂም እና ቤት ሁለቱም', gymHomeSub: 'በሁለቱም እለዋወጣለሁ', foodQuestion: 'የምግብ ምርጫዎችዎ ምንድን ናቸው?', foodSub: 'የሚመለከቱዎትን ሁሉ ይምረጡ።', meatEater: 'ስጋ ተመጋቢ', meatSub: 'ስጋ በመደበኛነት እበላለሁ', vegetarian: 'ቬጀቴሪያን', vegetarianSub: 'ስጋ አልበላም', regularFasting: 'በመደበኛነት እጾማለሁ', fastingSub: 'ሳምንታዊ ወይም ወቅታዊ ጾም', ethiopianDiet: 'የኢትዮጵያ ምግብ', ethiopianDietSub: 'እንጀራ፣ ሽሮ፣ ጥብስ እና ሌሎች',
  personalQuestion: 'ስለራስዎ ይንገሩን።', personalSub: 'ይህ እቅድዎን በትክክል እንድናበጅ ይረዳናል።', analysing: 'መገለጫዎን በመተንተን ላይ...', analysingSub: 'በቁመትዎ፣ በእድሜዎ እና በግብዎ መሰረት ተስማሚ ክብደትዎን በማስላት ላይ', gender: 'ጾታ', male: 'ወንድ', female: 'ሴት', age: 'ዕድሜ', heightCm: 'ቁመት (ሴ.ሜ.)', currentWeight: 'የአሁኑ ክብደት (ኪ.ግ.)', calculateIdeal: 'ተስማሚ ክብደቴን አስላ', idealWeight: 'ተስማሚ ክብደትዎ', idealExplanation: 'በቁመትዎ፣ በእድሜዎ እና በግብዎ መሰረት ይህ ጤናማ እና ሊደረስበት የሚችል የዒላማ ክብደት ነው።', accept: 'ተቀበል', setOwnGoal: 'የራሴን ግብ አስቀምጥ', goalWeightSet: 'የግብ ክብደት ተቀምጧል', goalWeight: 'የእኔ የግብ ክብደት (ኪ.ግ.)', confirmGoal: 'ግብ አረጋግጥ', locationQuestion: 'የት ይኖራሉ?', locationSub: 'ከአካባቢዎ ማህበረሰብ ጋር እንድናገናኝዎ ይረዳናል።', unitedKingdom: 'ዩናይትድ ኪንግደም', unitedKingdomSub: 'እንግሊዝ፣ ስኮትላንድ፣ ዌልስ፣ ሰሜን አየርላንድ', unitedStates: 'ዩናይትድ ስቴትስ', unitedStatesSub: 'ሁሉም የአሜሪካ ግዛቶች', europe: 'አውሮፓ', europeSub: 'ስዊድን፣ ጀርመን፣ ኖርዌይ እና ሌሎች', canada: 'ካናዳ', canadaSub: 'ሁሉም የካናዳ ግዛቶች', ethiopia: 'ኢትዮጵያ', ethiopiaSub: 'በኢትዮጵያ የሚኖሩ', somewhereElse: 'ሌላ ቦታ', otherCountry: 'ሌላ ሀገር', injuryQuestion: 'ጉዳት ወይም ገደብ አለዎት?', injurySub: 'እቅድዎ ከእነዚህ ጋር እንዲስማማ እናደርጋለን። ከሌለ ይዝለሉ።', backPain: 'የጀርባ ህመም', backPainSub: 'የታችኛው ወይም የላይኛው ጀርባ ችግር', kneeProblems: 'የጉልበት ችግር', kneeSub: 'ህመም ወይም የቀድሞ ጉዳት', shoulderIssues: 'የትከሻ ችግር', shoulderSub: 'የመገጣጠሚያ ወይም የጡንቻ ህመም', wristPain: 'የእጅ አንጓ ህመም', wristSub: 'የእጅ አንጓ ወይም የቀንድ ክንድ ህመም', anklePain: 'የቁርጭምጭሚት ህመም', ankleSub: 'የቁርጭምጭሚት ወይም የእግር ችግር', noInjuries: 'ጉዳት የለም', noInjuriesSub: 'ለመጀመር ዝግጁ ነኝ', other: 'ሌላ', otherInjurySub: 'ገደብዎን ለመግለጽ ይንኩ', describeInjury: 'ጉዳትዎን ወይም ገደብዎን ይግለጹ...', finish: 'ጨርስ', planReady: 'እቅድዎ ዝግጁ ነው።', planReadySub: 'ወደ Fitopia እንኳን ደህና መጡ። ሁሉም ለእርስዎ ተበጅቷል። እንጀምር።', customPlan: 'የተበጀ እቅድ', aiCoach: 'AI አሰልጣኝ', seePlan: 'እቅዴን አይ',
};

export function getTabTranslation(language) {
  return language === 'Amharic' ? amharic : english;
}
